config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get "videos/search", to: "videos#search"
  root to:"videos#index"
  resources :videos, only: [:new, :create, :destroy, :edit, :update, :show] do
    resources :comments
  end
  post "videos/:video_id/comments/new", to: "comments#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
end

app/models/video.rb
class Video < ApplicationRecord
    has_many :comments
    belongs_to :category, optional: true

    validates :url, :category, presence: true
    validates :title, presence: true, length: { minimum: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @videos_category = Video.where("category_id = ?", params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :favorite)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:author, :comment, :video_id)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

    before_action :set_video, only: [:edit, :update, :destroy]

    def index
        @videos = Video.joins(:category).merge(Category.where(favorite: true))
    end

    def new
        @video = Video.new
        @categories = Category.all
    end

    def create
        @video = Video.new video_params
        if @video.save
            flash[:notice] = "Vídeo salvo com sucesso!"
            redirect_to root_url
        else
            set_render :new
        end
    end

    def show
        @video = Video.where("id = ?", params[:id])
    end

    def edit
        set_render :edit
    end

    def update
        if @video.update video_params
            flash[:notice] = "Vídeo atualizado com sucesso!"
            redirect_to root_url
        else
            set_render :edit
        end
    end

    def destroy
        @video.destroy
        redirect_to root_url
    end

    def search
        @title = params[:title]
        @videos = Video.where "title like ?", "%#{@title}%"
    end

    private

    def video_params
        params.require(:video).permit(:title, :url, :category_id)
    end

    def set_video
        @video = Video.find(params[:id])
    end

    def set_render(view)
        @categories = Category.all
        render view
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :favorito %>
    <%= form.check_box :favorite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Ver', @category %> |
<%= link_to 'Voltar', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Favorito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.favorite %></td>
        <td><%= link_to 'Ver vídeos', category, class: "btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_category_path(category), class: "btn btn-info" %></td>
        <td><%= link_to 'Deletar', category, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar Categoria', new_category_path, class: "btn btn-primary" %>

app/views/categories/new.html.erb
<h1>Nova Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voltar', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Título</td>
            <td>URL</td>
            <td>Categoria</td>
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @videos_category %>
    </tbody>
</table>

<%= link_to 'Editar', edit_category_path(@category), class: "btn btn-info" %> |
<%= link_to 'Voltar', categories_path, class: "btn btn-primary" %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, url: new_video_comment_path) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :video_id %>
    <%= form.text_field :video_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_video_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Voltar', video_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Video:</strong>
  <%= @comment.video %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vídeo Fácil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar brand: "Vídeo Fácil", brand_link: root_url do %>
    <%= menu_group do %>
      <%= menu_item "Adicionar novo vídeo", new_video_path %>
      <%= menu_item "Categorias", categories_path %>
    <% end %>
    <%= form_tag videos_search_path, method: :get, class:"navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :title, @title, class: "form-control" %>
        <%= button_to "Buscar", nil, class: "btn btn-default" %>
      </div>
    <% end %>
  <% end %>
    <div class = "container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<% @video.errors.full_messages.each do |msg| %>
    <div class= "alert alert-danger" role="alert">
        <%= msg %>
    </div>
<% end %>

<%= form_for @video do |form|  %>
<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
        <%= form.label :Título %>
        <%= form.text_field :title, class:"form-control" %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <%= form.label :URL %>
            <%= form.text_field :url, class:"form-control" %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-2">
        <div class="form-group">
            <%= form.label :categoria %>
            <%= form.collection_select :category_id, @categories, :id, :title, {} ,class:"form-control" %>
        </div>
    </div>
</div>

<%= form.submit action_text, class: "btn btn-primary" %>
<% end %>

app/views/videos/_video.html.erb
<tr>
    <td><%= video.title %></td>
    <td><%= video.url %></td>
    <td><%= video.category.title %></td>
    <td><%= link_to "Ver vídeo", video_path(video), class: "btn btn-primary"%>
    <td><%= link_to "Editar", edit_video_path(video), class:"btn btn-info" %></td>
    <td><%= button_to "Deletar", video, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza de que deseja remover permanentemente este vídeo?"} %></td>
</tr>

app/views/videos/edit.html.erb
<%= render partial:"form", locals: {action_text: "Atualizar"} %>

app/views/videos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"> 
        <%= flash[:notice] %>
    </div>
<% end %>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Título</td>
            <td>URL</td>
            <td>Categoria</td>
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @videos %>
    </tbody>
</table>

app/views/videos/new.html.erb
<%= render partial:"form", locals: {action_text: "Criar"} %>

app/views/videos/search.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Título</td>
            <td>URL</td>
            <td>Categoria</td>
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @videos %>
    </tbody>
</table>

app/views/videos/show.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Título</td>
            <td>URL</td>
            <td>Categoria</td>
        </tr>
    </thead>
    <tbody>
        <% @video.each do |v|%>
        <tr>
            <td><%= v.title %></td>
            <td><%= v.url %></td>
            <td><%= v.category.title %></td>
        </tr>
    </tbody>
</table>

<p style="text-align:center">
    <% video = YouTubeAddy.extract_video_id(v.url)%>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= video %>"  title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>
        <% end %>
<%= link_to 'Voltar', root_path, class: "btn btn-primary" %>